/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "gtfs-realtime.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(transit_realtime_FeedMessage, transit_realtime_FeedMessage, 2)


PB_BIND(transit_realtime_FeedHeader, transit_realtime_FeedHeader, 2)


PB_BIND(transit_realtime_FeedEntity, transit_realtime_FeedEntity, 2)


PB_BIND(transit_realtime_TripUpdate, transit_realtime_TripUpdate, 2)


PB_BIND(transit_realtime_TripUpdate_StopTimeEvent, transit_realtime_TripUpdate_StopTimeEvent, 2)


PB_BIND(transit_realtime_TripUpdate_StopTimeUpdate, transit_realtime_TripUpdate_StopTimeUpdate, 2)


PB_BIND(transit_realtime_TripUpdate_StopTimeUpdate_StopTimeProperties, transit_realtime_TripUpdate_StopTimeUpdate_StopTimeProperties, 2)


PB_BIND(transit_realtime_TripUpdate_TripProperties, transit_realtime_TripUpdate_TripProperties, 2)


PB_BIND(transit_realtime_VehiclePosition, transit_realtime_VehiclePosition, 2)


PB_BIND(transit_realtime_VehiclePosition_CarriageDetails, transit_realtime_VehiclePosition_CarriageDetails, 2)


PB_BIND(transit_realtime_Alert, transit_realtime_Alert, 2)


PB_BIND(transit_realtime_TimeRange, transit_realtime_TimeRange, 2)


PB_BIND(transit_realtime_Position, transit_realtime_Position, 2)


PB_BIND(transit_realtime_TripDescriptor, transit_realtime_TripDescriptor, 2)


PB_BIND(transit_realtime_TripDescriptor_ModifiedTripSelector, transit_realtime_TripDescriptor_ModifiedTripSelector, 2)


PB_BIND(transit_realtime_VehicleDescriptor, transit_realtime_VehicleDescriptor, 2)


PB_BIND(transit_realtime_EntitySelector, transit_realtime_EntitySelector, 2)


PB_BIND(transit_realtime_TranslatedString, transit_realtime_TranslatedString, 2)


PB_BIND(transit_realtime_TranslatedString_Translation, transit_realtime_TranslatedString_Translation, 2)


PB_BIND(transit_realtime_TranslatedImage, transit_realtime_TranslatedImage, 2)


PB_BIND(transit_realtime_TranslatedImage_LocalizedImage, transit_realtime_TranslatedImage_LocalizedImage, 2)


PB_BIND(transit_realtime_Shape, transit_realtime_Shape, 2)


PB_BIND(transit_realtime_Stop, transit_realtime_Stop, 2)


PB_BIND(transit_realtime_TripModifications, transit_realtime_TripModifications, 2)


PB_BIND(transit_realtime_TripModifications_Modification, transit_realtime_TripModifications_Modification, 2)


PB_BIND(transit_realtime_TripModifications_SelectedTrips, transit_realtime_TripModifications_SelectedTrips, 2)


PB_BIND(transit_realtime_StopSelector, transit_realtime_StopSelector, 2)


PB_BIND(transit_realtime_ReplacementStop, transit_realtime_ReplacementStop, 2)



























#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

